# Generated by Django 3.1.8 on 2021-05-01 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseNumber', models.IntegerField(unique=True)),
                ('personName', models.CharField(max_length=200)),
                ('identityDocumentNumber', models.CharField(max_length=7)),
                ('birthDate', models.DateField()),
                ('symptomsOnsetDate', models.DateField()),
                ('infectionConfirmationDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseEventNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finder.case')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('staffNumber', models.CharField(max_length=200)),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venueName', models.CharField(max_length=200)),
                ('venueLocation', models.CharField(max_length=200)),
                ('venueAddress', models.CharField(max_length=200)),
                ('venueXCoordinates', models.DecimalField(decimal_places=10, max_digits=10)),
                ('venueYCoordinates', models.DecimalField(decimal_places=10, max_digits=10)),
                ('eventDate', models.DateField()),
                ('eventDescriptipn', models.CharField(max_length=200)),
                ('numberOfPeople', models.IntegerField()),
                ('people', models.ManyToManyField(through='Finder.CaseEvent', to='Finder.Case')),
            ],
        ),
        migrations.AddField(
            model_name='caseevent',
            name='caseEventVenueId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finder.event'),
        ),
    ]
