# Generated by Django 3.1.8 on 2021-05-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finder', '0002_auto_20210504_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venueAddress',
            field=models.CharField(max_length=200, null='True'),
        ),
    ]
