# Generated by Django 3.1.8 on 2021-05-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finder', '0003_auto_20210504_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venueXCoordinates',
            field=models.DecimalField(decimal_places=5, max_digits=20, null='True'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venueYCoordinates',
            field=models.DecimalField(decimal_places=5, max_digits=20, null='True'),
        ),
    ]
